pipeline {
    agent {
        docker {
            image 'mcr.microsoft.com/dotnet/sdk:6.0' // Usa una imagen oficial de .NET SDK
            args '-u root:root' // Permite instalar o escribir si hace falta
        }
    }

    environment {
        DOTNET_CLI_TELEMETRY_OPTOUT = '1'
        DOTNET_SKIP_FIRST_TIME_EXPERIENCE = '1'
    }

    options {
        timestamps()
    }

    stages {
        stage('Checkout') {
            steps {
                echo 'Clonando el repositorio...'
                checkout scm
            }
        }

        stage('Restaurar dependencias') {
            steps {
                sh 'dotnet restore anotaciones/anotaciones_csharp/main.csproj'
                sh 'dotnet restore anotaciones/test_csharp/test.csproj'
            }
        }

        stage('Compilar') {
            steps {
                  sh 'dotnet build anotaciones/anotaciones_csharp/main.csproj --configuration Release'
                  sh 'dotnet build anotaciones/test_csharp/test.csproj --configuration Release'
            }
        }

        stage('Ejecutar Tests') {
            steps {
                sh 'dotnet test anotaciones/test_csharp/test.csproj --logger trx;LogFileName=test_results.trx'
            }
        }

         stage('Convertir TRX a JUnit XML') {
            steps {
                // Instala trx2junit si no está disponible
                sh 'dotnet tool install -g trx2junit || true'
                // Convierte el archivo TRX generado
                sh 'trx2junit anotaciones/test_csharp/TestResults/test_results.trx'
            }
        }

        stage('Publicar resultados de test') {
            steps {
                junit 'anotaciones/test_csharp/TestResults/test_results.xml'
            }
        }

    }

    post {
        success {
            echo 'Pipeline finalizada con éxito.'
        }

        failure {
            echo 'La compilación o pruebas fallaron.'
        }
    }
}
